name: snowflake-demo
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.10
  - numpy 
  - pandas 
  - pyarrow 
  - jupyterlab 
  - tabulate
  - sqlglot
  - snowflake-snowpark-python=1.16.0
  - snowflake-ml-python=1.5.1
  - notebook
